ecom/core/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),


]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [

    #404 error page
    path('404',views.Error404, name='404'),

    
    path('admin/', admin.site.urls),
    path('base/', views.Base,name='base'),
    path('',views.Home, name='home'),
    path('about',views.AboutUs, name="about"),
    path('contact',views.ContactUs, name='contact'),
    path('blog', views.BlogView, name='blogs'),
    path('faq',views.Faq, name='faq'),
    
    path('blog/<slug:slug>',views.BlogDetail, name='blog_detail'),
    path('shop',views.Shop, name='shop'),
    path('shop/filter-data',views.filter_data,name="filter-data"),

    path('product/<slug:slug>',views.ProductDetail, name='product_detail'),
    path('products/<slug:slug>',views.UpcomingProductDetail, name='up_product_detail'),
    path('account/login',views.MyAccount, name='handlelogin'),
    path('account/register',views.MyAccountSignup, name='handlesignup'),
    path('account/profile',views.Profile, name='profile'),
    path('account/profile/update', views.ProfileUpdate, name='profile_update'),

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    path('checkout/',views.Checkout,name='checkout'),
    path('cart/checkout/placeorder', views.PlaceOrder, name='placeorder'),
    path('success/',views.Success, name='success'),


    path('accounts/', include('django.contrib.auth.urls'))


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from datetime import datetime


class Slider(models.Model):

    discount_deal = (
        ('HOT-DEALS', 'HOTDEALS') ,
        ('NEW-ARRIVALS', 'NEW-ARRIVALS')
    )
    image = models.ImageField(upload_to='media/slider_images', null=True)
    discount_deal = models.CharField(choices=discount_deal, max_length=100)
    sale = models.IntegerField()
    brand_name = models.CharField(max_length=200)
    discount = models.IntegerField()
    link = models.CharField(max_length=500)

    def __str__(self) :
        return self.brand_name


class BannerArea(models.Model):
    image = models.ImageField(upload_to='media/banner_images')
    discount_deal = models.CharField(max_length=200)
    quote = models.CharField(max_length=200)
    offer_description = models.CharField(max_length=200, null=True)
    link = models.CharField(max_length=500, null=True)

    def __str__(self) :
        return self.quote



class MainCategory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name
    
class Category(models.Model):
    main_category = models.ForeignKey(MainCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name + "--" + self.main_category.name
    
class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name

class Section(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name
    
    
class Color(models.Model):
    code = models.CharField(max_length=100)

    def __str__(self) :
        return self.code

class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) :
        return self.name

    
class Product(models.Model):
    total_quantity = models.IntegerField()
    availability = models.IntegerField()
    product_name = models.CharField(max_length=100)
    featured_image = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    discount = models.IntegerField()
    tax = models.IntegerField(null=True)
    product_information = RichTextField()
    model_name = models.CharField(max_length=100)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True)
    tags = models.CharField(max_length=100)
    description = RichTextField()
    section = models.ForeignKey(Section, on_delete=models.DO_NOTHING)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self) :
        return self.product_name
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("product_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "core_Product"

def create_slug(instance, new_slug=None):
    slug = slugify(instance.product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Product)



class CouponCode(models.Model):
    code = models.CharField(max_length=100)
    discount = models.IntegerField()

    def __str__(self) :
        return self.code

    
class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=200)

class AdditionalInformation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.CharField(max_length=100)
    detail = models.CharField(max_length=100)




class UpcomingProduct(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/upcoming_product_images', null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self) :
        return self.name
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("up_product_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "core_UpcomingProduct"

def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, UpcomingProduct)


class UpcomingProductImages(models.Model):
    product = models.ForeignKey(UpcomingProduct, on_delete=models.CASCADE)
    image = models.CharField(max_length=100)

class BlogSection(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self) :
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    posted_by = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/blogs')
    posted_date = models.DateField(auto_now_add=True)
    tags = models.CharField(max_length=100, null=True)
    section = models.ForeignKey(BlogSection, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    


    def __str__(self) :
        return self.title
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("blog_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "core_Blog"

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Blog)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    postcode = models.IntegerField(null=True)
    email = models.EmailField()
    phone = models.IntegerField()
    amount = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    paid = models.BooleanField(default=False, null=True)
    date =models.DateField(default=datetime.today)

    def __str__(self) :
        return self.first_name
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=100)
    quantity = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    total = models.CharField(max_length=100)

    def __str__(self) :
        return self.product
    

ecom/templates/includes/footer.html
{% load static %}
<footer>
    <div class="fotter-area d-dark-bg">
        <div class="footer__top pt-80 pb-15">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-4 order-last-md">
                        <div class="row">
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Customer Care</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'faq' %}">New Customers</a></li>
                                                <li><a href="{% url 'faq' %}">How to use Account</a></li>
                                                <li><a href="{% url 'faq' %}">Placing an Order</a></li>
                                                
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Customer Service</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'faq' %}">Help Center</a></li>
                                                <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                                <li><a href="{% url 'faq' %}">Policies &amp; Rules</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-8 order-first-md">
                        <div class="footer__top-left">
                            <div class="row">

                                <div class="col-xl-7 col-lg-6 col-md-6 col-sm-6">
                                    <div class="row">

                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                            <div class="footer__widget">
                                                <div class="footer__widget-title">
                                                    <h4>My Account</h4>
                                                </div>
                                                <div class="footer__widget-content">
                                                    <div class="footer__link">
                                                        <ul>
                                                            <li><a href="faq.html">Product Support</a></li>
                                                            <li><a href="checkout.html">Checkout</a></li>
                                                            <li><a href="cart.html">Shopping Cart</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                <div class="footer__widget">
                                    <div class="footer__widget-title">
                                        <h4>Quick Links</h4>
                                    </div>
                                    <div class="footer__widget-content">
                                        <div class="footer__link">
                                            <ul>
                                                <li><a href="{% url 'contact' %}">Store Location</a></li>
                                                <li><a href="my-account.html">My account</a></li>
                                                <li><a href="{% url 'faq' %}">FAQs</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div></div>
                                </div><div class="col-xl-5 col-lg-6 col-md-6 col-sm-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title mb-20">
                                            <h4>About The Store</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <p class="footer-text mb-35">Our mission statement is to provide the absolute best customer experience available in the Electronic industry without exception.</p>
                                            <div class="footer__hotline d-flex align-items-center mb-10">
                                                <div class="icon mr-15">
                                                    <i class="fal fa-headset"></i>
                                                </div>
                                                <div class="text">
                                                    <h4>Got Question? Call us 24/7!</h4>
                                                    <span><a href="tel:100-123-456-7890">(+91) 123 456 7890</a></span>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__bottom">
            <div class="container">
                <div class="footer__bottom-content pt-55 pb-45 ">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="footer__links text-center mb-4 ">
                                <p>
                                    <a href="{% url 'home' %}">Online Shopping</a>
                                    <a href="{% url 'home' %}">Promotions</a>
                                    <a href="faq.html">My Orders</a>
                                    <a href="{% url 'faq' %}">Help</a>
                                    <a href="{% url 'faq' %}">Customer Service</a>
                                    <a href="{% url 'faq' %}">Support</a>
                                    <a href="{% url 'home' %}">Most Populars</a>
                                    <a href="{% url 'home' %}">New Arrivals</a>
                                    <a href="{% url 'home' %}">Special Products </a>
                                    <a href="{% url 'home' %}">Manufacturers</a>
                                    <br>
                                    
                                </p>
                            </div>
                            <div class="payment-image text-center mb-25 ">
                                <a href="contact.html"><img src="{% static 'assets/img/payment/payment.png' %}" alt=""></a>
                            </div>
                            <div class="copy-right-area text-center">
                                <p>Copyright © <span>Opencart.</span> All Rights Reserved. Design and Developed <a href="#"><span class="main-color">Vishnu Surendran.</span></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

ecom/templates/includes/header.html
{% load static %}
<header class="header d-blue-bg">
    <div class="header-top">
        <div class="container">
            <div class="header-inner">
                <div class="row align-items-center">
                    <div class="col-xl-6 col-lg-7">
                        <div class="header-inner-start">
                            
                            
                            <div class="support d-none d-sm-block">
                                {% if user.is_authenticated %}
                                <p>Time to Experience The Online Shopping | 
                                    {% if user.first_name == "" %}
                                        {{user.username}}
                                    {% else %}
                                        {{user.first_name}} {{user.last_name}}
                                    {% endif %}

                                </p>
                                {% else %}
                                <p>Plese Login | Get access to your Orders, Wishlist and Recommendations</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-5 d-none d-lg-block">
                        <div class="header-inner-end text-md-end">
                            <div class="ovic-menu-wrapper">
                                <!-- <ul>
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="contact.html">Order Tracking</a></li>
                                    <li><a href="contact.html">Contact Us</a></li>
                                    <li><a href="faq.html">FAQs</a></li>
                                </ul> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-mid">
        <div class="container">
            <div class="heade-mid-inner">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                        <div class="header__info">
                            <div class="logo">
                                <a href="{% url 'home' %}" class="logo-image"><img
                                        src="{% static 'assets/img/logo/logo9.svg' %}" alt="logo"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                        <div class="header__search">
                            <form action="#">
                                <div class="header__search-box">
                                    <input class="search-input" type="text" placeholder="I'm shopping for...">
                                    <button class="button" type="submit"><i class="far fa-search"></i></button>
                                </div>
                                <div class="header__search-cat">
                                    <select>
                                        <option>All Categories</option>
                                        {% for i in main_category%}
                                            {% for cat in i.category_set.all %}
                                        <option>{{cat.name}}</option>
                                        {% endfor %}
                                        {% endfor %}
                                        
                                    </select>
                                </div>
                            </form>
                        </div>
                    </div>

                    {% include 'includes/models.html' %}


                </div>
            </div>
        </div>
    </div>
    <div class="header__bottom">
        <div class="container">
            <div class="row g-0 align-items-center">
                <div class="col-lg-3">
                    <div class="cat__menu-wrapper side-border d-none d-lg-block">
                        <div class="cat-toggle">
                            <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i>
                                Shop by department</button>
                            <div class="cat__menu">
                                <nav id="mobile-menu" style="display: block;">
                                    <ul>

                                        {% for i in main_category %}

                                        <li>
                                            <a href="{% url 'shop' %}"> {{ i.name }} <i class="far fa-angle-down"></i></a>
                                            <ul class="mega-menu">

                                                {% for cat in i.category_set.all %}

                                                <li><a href="{% url 'shop' %}">{{cat.name}}</a>
                                                    <ul class="mega-item">
                                                        {% for sub_cat in cat.subcategory_set.all %}
                                                        <li><a href="product-details.html">{{sub_cat.name}}</a></li>
                                                        {% endfor %}
                                                        
                                                    </ul>
                                                </li>
                                                {% endfor %}
  
                                            </ul>
                                        </li>

                                        {% endfor %}
                                        
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-3">
                    <div class="header__bottom-left d-flex d-xl-block align-items-center">
                        <div class="side-menu d-lg-none mr-20">
                            <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i
                                    class="fas fa-bars"></i></button>
                        </div>
                        <div class="main-menu d-none d-lg-block">
                            <nav>
                                <ul>
                                    <li>
                                        <a href="{% url 'home' %}" class="active">Home </a>
                                        
                                    </li>
                                    <li><a href="{% url 'shop' %}">Product</a></li>
                                    <li><a href="{% url 'about' %}">About Us</a></li>
                                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                    <li><a href="{% url 'blogs' %}">Blog </a></li>
                                    
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-9">
                    <div class="shopeing-text text-sm-end">
                        <p>Spend ₹150 more and get free shipping!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- offcanvas area start -->
<div class="offcanvas__area">
    <div class="offcanvas__wrapper">
        <div class="offcanvas__close">
            <button class="offcanvas__close-btn" id="offcanvas__close-btn">
                <i class="fal fa-times"></i>
            </button>
        </div>
        <div class="offcanvas__content">
            <div class="offcanvas__logo mb-40">
                <a href="index.html">
                    <img src="assets/img/logo/logo-white.png" alt="logo">
                </a>
            </div>
            <div class="offcanvas__search mb-25">
                <form action="#">
                    <input type="text" placeholder="What are you searching for?">
                    <button type="submit"><i class="far fa-search"></i></button>
                </form>
            </div>
            <div class="mobile-menu fix"></div>
            <div class="offcanvas__action">

            </div>
        </div>
    </div>
</div>
<!-- offcanvas area end -->
<div class="body-overlay"></div>
<!-- offcanvas area end -->

ecom/templates/includes/models.html
<div class="col-xl-4 col-lg-5 col-md-8 col-sm-8">
    <div class="header-action">
        {% if user.is_authenticated %}
        <div class="block-userlink">
            <a class="icon-link" href="{% url 'profile' %}">
                <i class="flaticon-user"></i>
                <span class="text-center">
                    <span class="sub "> Profile</span>
                </span>
            </a>
        </div>
        {% else %}

        <div class="block-userlink">
            <a class="icon-link" href="{% url 'login' %}">
                <i class="flaticon-user"></i>
                <span class="text">
                    <span class="sub">Login </span>
                    My Account </span>
            </a>
        </div>


        {% endif %}
        <div class="block-wishlist action">
            <a class="icon-link" href="wishlist.html">
                <i class="flaticon-heart"></i>
                <span class="count">0</span>
                <span class="text">
                    <span class="sub"></span>
                    Wishlist </span>
            </a>
        </div>
        <div class="block-cart action">
            <a class="icon-link" href="{% url 'cart_detail' %}">
                <i class="flaticon-shopping-bag"></i>
                <span class="count">{{request.session.cart|length}}</span>
                <span class="text">
                    <span class="sub">Your Cart:</span>
                    </span>
            </a>
            <div class="cart">
                <div class="cart__mini">
                    <ul>
                        <li>
                            <div class="cart__title">
                                <h4>Your Cart</h4>
                                <span>({{request.session.cart|length}} Item in Cart)</span>
                            </div>
                        </li>

                        {% for key,value in request.session.cart.items %}
                        <li>
                            <div
                                class="cart__item d-flex justify-content-between align-items-center">
                                <div class="cart__inner d-flex">
                                    <div class="cart__thumb">
                                        <a href="{% url 'cart_detail' %}">
                                            <img src="{{value.featured_image}}" alt="">
                                        </a>
                                    </div>
                                    <div class="cart__details">
                                        <h6><a href="{% url 'cart_detail' %}"> {{value.product_name}}</a></h6>
                                        <div class="cart__price">
                                            <span>₹{{value.price}}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="cart__del">
                                    <a href="{% url 'item_clear' key %}"><i class="fal fa-times"></i></a>
                                </div>
                            </div>
                        </li>
                        {% endfor %}


                        <li>
                            <div
                                class="cart__sub d-flex justify-content-between align-items-center">
                                <h6>Subtotal</h6>
                                <span class="cart__sub-total">₹{{cart_total_amount}}</span>
                            </div>
                        </li>
                        <li>
                            <a href="{% url 'cart_detail' %}" class="wc-cart mb-10">View cart</a>
                            <a href="{% url 'checkout' %}" class="wc-checkout">Checkout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>